- name: inject faults
  hosts: nagios_clients
  become: true
  tasks:
    - name: Add packet loss on eth1 and delay
      ansible.builtin.command: tc qdisc replace dev eth1 root netem loss 60% delay 2000ms

    - name: Pause for 5 minutes
      ansible.builtin.pause:
        minutes: 5

    - name: Cleanup TC qdiscs
      ansible.builtin.command: tc qdisc del dev eth1 root netem
      tags: cleanup
      ignore_errors: true

    - name: Pause for 1 minute
      ansible.builtin.pause:
        minutes: 1
    
    - name: Disable networking
      ansible.builtin.command: ip link set eth1 down
    
    - name: Pause for 5 minutes
      ansible.builtin.pause:
        minutes: 5

    - name: Enable networking
      ansible.builtin.service:
        ansible.builtin.command: ip link set eth1 up

    - name: Disable apache
      ansible.builtin.service:
          name: apache2
          state: stopped

    - name: Pause for 5 minutes
      ansible.builtin.pause:
        minutes: 5
    