- name: Install Nagios server
  hosts: nagios_server
  # Normally, the pass should be encrypted with Ansible vault.
  # I'm including this in plaintext to ease demonstration and replicability.
  vars:
    nagios_admin_user: nagiosadmin
    nagios_admin_password: pass
    nagios_hosts:
      - { name: node2, address: 192.168.50.12 }
      - { name: node3, address: 192.168.50.13 }
      - { name: node4, address: 192.168.50.14 }
  become: true
  tasks:
    - name: Install Nagios
      ansible.builtin.apt:
        name:
          - nagios4
          - nagios-plugins
          - nagios-nrpe-plugin
          - apache2
          - python3-passlib
        state: present
        update_cache: true

        
    - name: Enable auth_digest and CGI modules
      community.general.apache2_module:
        name: "{{ item }}"
        state: present
      loop:
        - auth_digest
        - cgi
      notify: restart apache
    
    - name: Set up Nagios web user
      ansible.builtin.copy:
        dest: /etc/nagios4/htdigest.users
        content: "{{ nagios_admin_user }}:Nagios4:{{ (nagios_admin_user ~ ':Nagios4:' ~ nagios_admin_password) | hash('md5') }}\n"
        owner: root
        group: www-data
        mode: "0640"
      notify: restart apache
        
    - name: Start Nagios service
      ansible.builtin.systemd:
        name: nagios4
        state: started
        enabled: true

    - name: Start Apache2 service
      ansible.builtin.systemd:
        name: apache2
        state: started
        enabled: true
    
    - name: Add host definitions for other hosts
      ansible.builtin.template:
        src: net_hosts.cfg.j2
        dest: /etc/nagios4/conf.d/net_hosts.cfg
        owner: root
        group: root
        mode: "0644"
      notify: restart nagios

    - name: Add service definitions
      ansible.builtin.template:
        src: net_services.cfg.j2
        dest: /etc/nagios4/conf.d/net_services.cfg
        owner: root
        group: root
        mode: "0644"
      notify: restart nagios

    - name: Enable nagios4 CGI configuration
      ansible.builtin.command: a2enconf nagios4-cgi
      args:
        creates: /etc/apache2/conf-enabled/nagios4-cgi.conf
      notify: restart apache

    # Enable authentication for Nagios
    - name: enable nagios auth
      ansible.builtin.lineinfile:
        path: /etc/nagios4/cgi.cfg
        regexp: '^use_authentication='
        line: use_authentication=1
      notify: restart nagios
    
    # Required for getting authentication to work with Nagios.
    # A lot of the configurations here were based on this tutorial:
    # https://discourse.ubuntu.com/t/nagios-core-4-installation-and-configuration/51519
    - name: edit nagios apache config
      ansible.builtin.lineinfile:
        path: /etc/nagios4/apache2.conf
        regexp: '{{ item.regexp }}'
        line: '{{ item.line }}'
      loop:
        - { regexp: '^(\s*)Require ip', line: '# Require ip' }
        - { regexp: '^(\s*)Require all\s+granted', line: '#Require all granted'}
        - { regexp: '^(\s*)#Require\s+valid-user', line: 'Require valid-user'}
        - { regexp: '^(\s*)<Files "cmd.cgi">', line: '#<Files "cmd.cgi">'}
        - { regexp: '^(\s*)</Files>', line: '#</Files>'}
        - { regexp: '^\s*AuthType', line: 'AuthType Digest' }
        - { regexp: '^\s*AuthName', line: 'AuthName "Nagios4"' }
        - { regexp: '^\s*AuthDigestProvider', line: 'AuthDigestProvider file' }
        - { regexp: '^\s*AuthUserFile', line: 'AuthUserFile /etc/nagios4/htdigest.users' }
    

    - name: Copy nagios apache2 config to apache2
      ansible.builtin.file:
        src: /etc/nagios4/apache2.conf
        dest: /etc/apache2/sites-available/nagios4.conf
        state: link
      notify: restart apache

    - name: Enable nagios4 site
      ansible.builtin.command: a2ensite nagios4.conf
      args:
        creates: /etc/apache2/sites-enabled/nagios4.conf
      notify: restart apache

    - name: Enable nagios4 initial state logging
      ansible.builtin.lineinfile:
        path: /etc/nagios4/nagios.cfg
        regexp: '^log_initial_states='
        line: 'log_initial_states=1'
      notify: restart nagios

  handlers:
    - name: restart nagios
      ansible.builtin.systemd:
        name: nagios4
        state: restarted
    - name: restart apache
      ansible.builtin.systemd:
        name: apache2
        state: restarted
