- name: Base setup
  hosts: all
  become: true
  tasks:
    # install iproute, if not already on machine.
    - name: Install iproute2 and other packages
      apt:
        name: 
          - iproute2
          - apache2
          - at
        state: present
        update_cache: yes

    - name: Enable at daemon
      ansible.builtin.systemd:
        name: atd
        state: started
        enabled: true

# Set up Nagios on server
- import_playbook: nagios_server.yml
# set up Nagios on client
- import_playbook: nagios_clients.yml
