require 'yaml'
# Load nodes:
nodes = YAML.load_file('nodes.yml')

# Set up Vagrant API ver 2
Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"

  # set up each node in nodes.yml 
  nodes.each do |node|
    config.vm.define node["name"] do |machine|
      machine.vm.hostname = node["name"]
      machine.vm.boot_timeout = 1000
      machine.vm.network "private_network", ip: node["ip"]
      machine.vm.provider "libvirt" do |libvirt|
        libvirt.memory = node["memory"]
        libvirt.cpus = node["cpus"]
        libvirt.driver = "kvm"
      end
    end
  end

  # set up provisions
  
  # Use Ansible
  config.vm.define nodes.last["name"] do |last|
    last.vm.provision "ansible" do |ansible|
      ansible.limit = "all"
      ansible.playbook = "playbooks/setup.yml"
      # create groups in inventory
      ansible.groups = { 
        "net" => nodes.map { |n| n["name"] } ,
        "nagios_server" => [nodes.first["name"]],
        "nagios_clients" => nodes.drop(1).map { |n| n["name"] }
      }
    end
  end
end
